name: Deploy to cPanel

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Deploy the entire repository content
        server-dir: ../../public_html/ # Target directory on your server
        port: 21
        # Options for cleaning up remote directory before deploying can be added here
        # e.g., dangerous-clean-slate: true # This would delete everything in server-dir first 